SET TRUENULLCREATE = OFF;
CREATE TABLE "GCG_5799_INV_ATTR" (
 "PART" CHAR(20),
 "LOC" CHAR(2),
 "MAKE" CHAR(50),
 "MODEL" CHAR(50),
 "DEFAULT_QTY" NUMERIC(4,0) );
SET TRUENULLCREATE = ON;
CREATE INDEX "GCG_5799_INV00" IN DICTIONARY  ON "GCG_5799_INV_ATTR" ( "PART", "LOC" );
CREATE INDEX "GCG_5799_INV01" IN DICTIONARY  ON "GCG_5799_INV_ATTR" ( "MAKE", "MODEL" );